kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: app-name
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZWEowZFhKbmIyMXpPbWRvY0Y5YWVXODBkRUpVTlc1bFRtMWtZM2wzUzFkT09XOWxWbWx0VW5ZMFExQXlTblV4UVRBPSJ9fX0=
